- typing-app/.dockerignore
- typing-app/Dockerfile
- typing-app/next.config.mjs
遅くなりましたがよろしくお願いします！
(省略)
- フロントエンドのコンテナを立てられるようにした
- github actions の設定など
- 無し
- 無し
:ok: build
```
$ docker build --no-cache --tag=su-its-typing-typing-app:latest .
[+] Building 83.9s (18/18) FINISHED                                                                 docker:default
=> [internal] load build definition from Dockerfile                                                          0.0s
=> => transferring dockerfile: 675B                                                                          0.0s
=> [internal] load metadata for docker.io/library/node:20.11-slim                                            1.0s
=> [internal] load metadata for docker.io/oven/bun:slim                                                      0.9s
=> [internal] load .dockerignore …
```
> フロントエンドのコンテナ立てるための Dockerfile を作成

- .github/actions/prepare-nodemodules/action.yml
- .github/workflows/build-app.yml
- .github/workflows/nodejsci.yml
- ~~nodejsci.yml~~ build-app.yml の追加
- develop ブランチへの PR 時に `npm run build` ~~し、それが成功したら `npm run lint` も~~やる
- ~~bunを使ってるけどnodeの知見で書いたので何となくというのとワンチャンbunやめるかもしれないのでnodejsという文言が入ってる~~
- typing-app の app を取って build-app にした
- ~~workflow file の分割等~~
- reviewdog の導入等
- 無し
- 無し
- 手元で [act](https://nektosact.com/) による動作確認を行った
- act はローカルで Github Actions の動作確認を行えるツールです
- キャッシュがある場合と無い場合、それからTypeScriptの文法エラーで失敗する場合、すべてについて想定通り動いてました
> ci[typing-app]: PR時にビルドする

- typing-server/api/cmd/main.go
- typing-server/docker-compose.dev.yml
- typing-server/docker-compose.yml
(省略)
- データベースのアドレスを環境変数 `DB_ADDR` から設定するように変更した
- 動作確認のために Cloud Run にデプロイするが、その段階で希望の値をセットしたかったため
- ドキュメントの整備
- 一応、書いたには書いたんですがここに含めると時間がかかりそうだったので省略しています
- 無し
- 無し
- 異なる環境変数を渡して go のプログラムが異なる接続先に接続しに行くことを確認した
```bash
$ docker compose down api
```
:ok_man: まず適当なアドレスを指定すると繋がらないことを確認
```bash
docker compose run --rm --env DB_ADDR=192.168.0.1:3306 api
[+] Creating 1/0
✔ Container typing-server-db-1  Running                                                                                                                                               0.0s
2024/03/10 05:04:21 INFO ent client is opened
2024/03/10 05:04:23 ERROR failed to create schema: %v !BADKEY="mysql: querying mysql version dial tcp 192.168.0.1:3306: connect: connection refused"
```
:ok_man: 次に docker-compose.yml の db …
> fix[typing-server]: 接続するDBのアドレスを環境変数で指定できるように

- typing-app/src/components/templates/GamePre.tsx
- 空白キー押下で次のページ(GameTyping.tsxの中身)に遷移
- 無し
- 空白キー押下で次のページに遷移
- 仮置きのボタンを廃止
- `bun run build`して動作することを確認
- 無し
> Feat/game screen/start button fixed

- .github/workflows/build-image.yml
- docker/compose.ci.yaml
- typing-app/.dockerignore
- typing-app/Dockerfile
fix #35
- `typing-app/Dockerfile` を yarn 用に修正した
- これによって失敗していた CI が回るはず！具体的な内容は issue 35 を見てください
- その他 `.dockerignore` に `.yarn` と `.dockerignore` を追加するなど
- 無し
- 無し
- 無し
- 手元で `docker compose build -f compose.ci.yaml app` を何回か行って正常に動作することを確認した
> yarn の移行に伴って壊れた CI を直す

- .github/workflows/deploy.yml
- デプロイ先のサーバで podman-compose コマンドを docker compose の代わりに使うことにした
- 無し
- 無し
- 無し
- 未
podman-compose は podman と直にしゃべるっぽくてなんか docker-compose より軽そうな気がする
RHEL で docker 使うとなると、基本的に docker のふりをした podman がバックエンドにいるので podman に乗っかれるなら乗っかった方がいいのかなっていう判断(ふわっと)
> ci: change docker compose -> podman-compose

- .github/workflows/golangci-lint.yml
- golangci-lint のワークフローが回る条件が on.push to main / develop だったが、これに `pathes: typing-server/**` の条件を追加した
- 無し
- 無し
- 無し
- 未検証
> ci: golangci-lint に on.push のパスを追加した

- typing-app/docs/api-usage.md
- typing-app/src/libs/api/index.ts
- バックエンド API を呼び出すコードを書いた ( #24 の続きといえば続きです)
- 無し
- 開発者目線では `client.GET("/healthcheck")`とするとヘルスチェック API を呼び出せるようになった
- 無し
- どのような動作確認を行ったのか？　結果はどうか？
RankingPageを下記のように書き換えて http://localhost:3000/ranking にアクセス。想定通り next.js サーバーから API にリクエストが飛んだこと。それと同時にブラウザからはAPIリクエストが飛ばなかったことを確認した。
```diff
-import RankingPage from "@/components/pages/Ranking";
+// import RankingPage from "@/components/pages/Ranking";
+import { client } from "@/libs/api";
-export default function Ranking() {
-  return <RankingPage />;
+export default async function Ranking() {
+  const { data, error } = await client.GET("/scores/ranking");
+
+  if (error) {
+    return <div>Error</div>;
+  }
+
+  return (
+    <div>
+      ranking data: {JSON.stringify(data)}
+    </div>
+  );
+  // return <RankingPage />;
}
```
> feat[typing-app]: バックエンドAPIを呼ぶクライアントを作成

- typing-app/src/components/molecules/LogoutButton.tsx
resolve https://github.com/su-its/typing/issues/90
LogoutButtonを押したときにCookieをリセットするloginを呼ぶようにした
なし
ログアウトできるようになる
なし
ローカルで確認
> feat:ログアウトボタンからlogoutを呼び出すように実装

- typing-app/__test__/components/UserCard.test.tsx
- typing-app/src/app/actions.ts
- typing-app/src/components/molecules/UserCard.tsx
resolve https://github.com/su-its/typing/issues/67
UserCardで表示するデータをAPIから取得したものに変更
テストの実装
なし
ログインするとユーザーカードに情報が表示されるようになる
なし
ローカル環境で確認
しずっぴーのいい画像があればこのブランチでつけます
> UserCardでAPIから取得したデータを使用

- typing-app/src/components/templates/GameResult.tsx
- リザルト画面において，「次へ」ボタンを「もう一度プレイする」ボタンに名前を変更
- 「ゲームを終了する」ボタンを追加した
- 無し
- リザルト画面において，「ゲームを終了する」ボタンか「もう一度プレイする」ボタンかどちらかを選択することができる
- 無し
- yarn buildが通ることを確認
```
yarn build
▲ Next.js 14.1.0
- Environments: .env
Creating an optimized production build ...
⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Compiler server unexpectedly exited with code: null and signal: SIGTERM
⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: …
```
> feat: リザルト画面で「ゲームを終了する」ボタンの追加

- typing-server/api/cmd/main.go
- https://github.com/orgs/su-its/projects/example-hogehoge-fugafuga
- シグナルハンドリングを修正
> fix: Fix server shutdown logic

- typing-app/src/components/templates/GameTyping.module.css
- #97
- 長文が BOX からはみ出ないようにした
- 自動でスクロールしたり現在のカーソル位置が順次上がっていったりはしない
- 長文が BOX からはみ出ないようになる
- 無し
お疲れのところとは思いますが、あと少しよろしくお願いします！ :bow:
> fix: 長文が BOX からはみ出るのを修正

- typing-app/src/components/pages/Game.tsx
resolve #105 
`/game`に直接アクセスした際に、ログイン状況をチェックしてログインしていなければ`/`にpush
なし
なし
ログインしていない状況での`/game`へのアクセス
ローカルで確認
`yarn dev`環境で実行すると、`strict mode`の影響によりtoastが二回出ます。
> /gameに直接アクセスした際にログイン状況をチェック

- typing-app/src/components/molecules/UserCard.tsx
- typing-app/src/components/organism/Header.tsx
- UserCard コンポーネントの横幅をタイトルの文字が切れない程度に広めに設定して Header から呼ぶように変更する
- UserCard コンポーネント自体も少し高さを低くする
- 無し
- (おそらく)フッターが見切れる症状がなくなる
- 拡大率125%のモニタでフッターが見切れなくなることを確認しました
- 無し
- next build OK
> UserCard の横幅を文字が切れない程度に広くする

- typing-server/api/repository/score.go
resolve https://github.com/su-its/typing/issues/130
resolve https://github.com/su-its/typing/issues/132
- スコアの登録時にレスポンスが500になるときがある
- ランキングが登録されていない時に空配列を返すように仕様に沿って修正
- このプルリクでやらないことは何か？（あれば。無いなら「無し」で OK）（やらない場合は、いつやるのかを明記する。）
- 何ができるようになるのか？（あれば。無いなら「無し」で OK）
- 何ができなくなるのか？（あれば。無いなら「無し」で OK）
- どのような動作確認を行ったのか？　結果はどうか？
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
> スコアが登録されていない時に空の配列を返すように修正

- typing-server/internal/domain/model/model.go
- typing-server/internal/domain/repository/error.go
- typing-server/internal/domain/repository/user_repository.go
- typing-server/internal/infra/ent/repository/ent_user_repository.go
- https://github.com/orgs/su-its/projects/example-hogehoge-fugafuga
- UserRepositoryにCreateUser functionを定義
- error.goに，学籍番号が重複した場合のエラーを定義
- EntUserRepositoryにCreateUser interfaceを作成
- EntUserRepositoryにCreateUser interfaceを実装
- 何ができるようになるのか？（あれば。無いなら「無し」で OK）
- 何ができなくなるのか？（あれば。無いなら「無し」で OK）
- どのような動作確認を行ったのか？　結果はどうか？
- レビュワーへの参考情報（実装上の懸念点や注意点などあれば記載）
> feat: ユーザー追加のためのリポジトリを定義，作成

- .github/workflows/build-image.yml
Why
Docker Image のPush回りのCIが落ちていた
What
Docker Bake Actionのバージョンをv5に上げた。
Details
こんなエラーが出ていたのでv5にした
Run docker/bake-action@v4
Error: docker/bake-action < v5 is not compatible with buildx >= 0.20.0, please update your workflow to latest docker/bake-action or use an older buildx version.
ref <https://github.com/su-its/typing/actions/runs/13560088353/job/37901504524#annotation:6:11>
> ci: Upgrade Docker Bake Action to v5

- typing-app/src/components/molecules/LoginModal.tsx
Why
#193 useFormStateはhooksが古いのでエラーが出ていた。
What
useFormState -> useActionStateに書き換え
LoginModalで出てたちょっとした赤字を修正
動作確認済み
> refactor: Update to useActionState for form state management

- docker/compose.ci.yaml
- CIでイメージをビルドする際にキャッシュされるGoのイメージのバージョンを上げた
- typing-server/Dockerfile 側のバージョンとずれていたため
- ローカルではCACHEと表示が出てキャッシュが効いている(そのレイヤーのビルドがスキップされている)ことを確認しました
- これがマージされてCIを何度か回してやっと本当に動作確認できると思います
```bash
cd docker
docker --debug buildx bake --allow=fs.read=../typing-app --allow=fs.read=../typing-server -f compose.ci.yaml
```
<details><summary>docker buildx bakeの結果</summary>
```
projects/su-its-typing/docker  ci/docker/update-golang-1.23.4 [$+] ➜ docker --debug buildx bake --allow=fs.read=../typing-app --allow=fs.read=../typing-server -f compose.ci.yaml
[+] Building 8.7s (41/41) FINISHED                                                                       docker:default
=> [internal] load local bake definitions                                                                         0.0s
=> => …
```
> ci: update the version of golang image to 1.23.4

- typing-app/Dockerfile
- typing-server/Dockerfile
- typing-server/Dockerfile.dev
- typing-appおよびtyping-serverのDockerfile(.dev)に対して出ていた警告を修正
警告の一例↓
> **The 'as' keyword should match the case of the 'from' keyword**: typing-app/Dockerfile#L14
> FromAsCasing: 'as' and 'FROM' keywords' casing do not match
> More info: https://docs.docker.com/go/dockerfile/rule/from-as-casing/
([適当な履歴](https://github.com/su-its/typing/actions/runs/13679515770)のAnnotationという欄から見られる)
- 修正したDockerfile(.dev)に対して`docker build --check`を実行し何も警告が出なくなった
> build: fix dockerfile warning

- typing-server/cmd/server/main.go
- typing-server/internal/interfaces/handler/score_handler.go
- typing-server/internal/interfaces/handler/score_handler_test.go
- typing-server/internal/interfaces/handler/user_handler.go
- typing-server/internal/interfaces/handler/user_handler_test.go
- typing-server/pkg/middleware/logging.go
エラー時に内容を正しくロギングできていなかった
スタック情報などは無いがとりあえず、暫定的にエラー箇所は特定できるレベルでロギングを行う。
またロギングミドルウェアのログタイプのルーティングも修正した
> fix(server): エラー時のロギングを改善

- typing-server/internal/infra/ent/repository/ent_score_repository.go
スコア登録に失敗する
最大スコア更新のフラグ判定処理のクエリを修正
isMax系の更新が漏れるケースがあり、Uniqueクエリを使うとエラーになるのでFirstを使う。
対処療法的な方法で根本的にはランキング計算の方法を変えていく必要がある #203 に起票ed
> fix(server): Unique検索のバグを回避するために、OnlyメソッドをFirstメソッドに変更
